version: "3.9"
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: angannondir-cloudflare
    cap_drop:
      - all
    environment:
      CF_API_TOKEN: ${ANGANNONDIR_CLOUDFLARE_TOKEN}
      DOMAINS: ${DOMAINS}
      PGID: ${PGID}
      PROXIED: "TRUE"
      PUID: ${PUID}
      TZ: ${TZ}
      IP6_PROVIDER: "none"
    network_mode: host
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: angannondir-npm-app
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_NAME: ${ANGANNONDIR_DB_DATABASE}
      DB_MYSQL_PASSWORD: ${ANGANNONDIR_DB_PASSWORD}
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${ANGANNONDIR_DB_USERNAME}
      DISABLE_IPV6: 'true'
    ports:
      - ${ANGANNONDIR_NPM_PORT_HTTP}:80
      - ${ANGANNONDIR_NPM_PORT_HTTPS}:443
      - ${ANGANNONDIR_NPM_PORT_ADMIN}:81
    restart: unless-stopped
    volumes:
      - nginx-proxy-manager-app:/data
      - nginx-proxy-manager-letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.labels.angannondir == true]

  db:
    image: yobasystems/alpine-mariadb:latest
    container_name: angannondir-npm-db
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${ANGANNONDIR_NPM_DATABASE}
      MYSQL_USER: ${ANGANNONDIR_NPM_USERNAME}
      MYSQL_PASSWORD: ${ANGANNONDIR_NPM_PASSWORD}
    restart: unless-stopped
    volumes:
      - ${ANGANNONDIR_DB_PATH}:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.labels.database == true]
volumes:
  nginx-proxy-manager-app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${ENEDOS_PATH}/angannondir/nginx-proxy-manager
  nginx-proxy-manager-letsencrypt:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${ENEDOS_PATH}/angannondir/nginx-proxy-manager/letsencrypt
