version: "3.9"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      VERSION: docker
      PLEX_CLAIM: ${NETHIADIL_PLEX_CLAIM}
    ports:
      - ${NETHIADIL_PLEX_PORT}:32400/tcp
    restart: unless-stopped
    volumes:
      - plex-app:/config
      - plex-media:/media
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.nethiadil == true]

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: nethiadil-stats
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - ${NETHIADIL_TAUTULLI_PORT}:8181
    restart: unless-stopped
    volumes:
      - tautulli-app:/config
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.nethiadil == true]

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: nethiadil-requests
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - ${NETHIADIL_OMBI_PORT}:3579
    restart: unless-stopped
    volumes:
      - ombi-app:/config
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.nethiadil == true]

  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: nethiadil-metadata
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    restart: unless-stopped
    volumes:
      - plex-meta-manager-app:/config
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.nethiadil == true]

volumes:
  plex-app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${ENEDOS_PATH}/nethiadil/plex
  plex-media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/media
  plex-meta-manager-app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${ENEDOS_PATH}/nethiadil/metadata
  ombi-app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${ENEDOS_PATH}/nethiadil/requests
  tautulli-app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${ENEDOS_PATH}/nethiadil/stats
